### ISSUE TITLE
Move to fsprojects?

### ISSUE THREAD

**Issue by dsyme** [fsprojects/matprovider#4]
Hi @luajalla,

Would you like to move this project to http://github.com/fsprojects?  That way we can more easily give the project multiple maintainers and integrate the pull requests which are listed here.  It would be good to have this provider put on a long-term stable basis.

If you would, please add an issue at https://github.com/fsprojects/FsProjectsAdmin/issues/

Many thanks,
Don

**Comment by luajalla** [comment]
I still need to properly integrate some changes implemented when people asked for more functionality. And resolve the issue with big files, otherwise it's not super-useful (that's also why pull request isn't merged). Unfortunately didn't have time (nor machine...) for that so far.

I don't mind moving it in fsprojects, but probably it makes sense to come up with a more stable solution first.

**Comment by dsyme** [comment]
It's probably better to just move it - one of the good things about moving is that various people (including me) can help you stabilize it - CI, writing docs, tests etc.

You have permissions to make the transfer - just use Settings in the project and transfer across.  Github adds redirects from the old URLs.

**Comment by luajalla** [comment]
The repo is transfered, just need to make the windows build green ^_^
